# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # the name of the filter set defined in config
    filter_sets:
        # use the default cache configuration
        cache: ~
        # the name of the "filter set"
        restaurant_thumb:
            # adjust the image quality to 100%
            quality: 100
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                thumbnail: { size: [480, 360], mode: outbound }
        activity_thumb:
            quality: 100
            filters:
                thumbnail: { size: [732, 427], mode: outbound }